apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-webapp
  template:
    metadata:
      labels:
        app: php-webapp
    spec:
      containers:
      - name: php-webapp
        image: php-webapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
