# Usa a imagem oficial do PHP como imagem pai
FROM php:7.4-apache

# Copia o script PHP para a raiz do documento do servidor Apache
COPY index.php /var/www/html/

# O Apache já está configurado para servir o conteúdo de /var/www/html/
# Não é necessário mais configuração
